export const words =
  "assetaudioauditavoidawardawarebadlybakerbasesbasicbasisbeachbeganbeginbegunbeingbelowbenchbillybirthblackblameblindblockbloodboardboostboothboundbrainbrandbreadbreakbreedbriefbringbroadbrokebrownbuildbuiltbuyercablecalifcarrycatchcausechainchairchartchasecheapcheckchestchiefchildchinachosecivilclaimclasscleanclearclickclockclosecoachcoastcouldcountcourtcovercraftcrashcreamcrimecrosscrowdcrowncurvecycledailydancedateddealtdeathdebutdelaydepthdoingdoubtdozendraftdramadrawndreamdressdrilldrinkdrivedrovedyingeagerearlyeartheighteliteemptyenemyenjoyenterentryequalerroreventeveryexactexistextrafaithfalsefaultfiberfieldfifthfiftyfightfinalfirstfixedflashfleetfloorfluidfocusforceforthfortyforumfoundframefrankfraudfreshfrontfruitfullyfunnygiantgivenglassglobegoinggracegradegrandgrantgrassgreatgreengrossgroupgrownguardguessguestguidehappyharryheartheavyhencehenryhorsehotelhousehumanidealimageindexinnerinputissuejapanjimmyjointjonesjudgeknownlabellargelaserlaterlaughlayerlearnleaseleastleavelegallevellewislightlimitlinksliveslocallogiclooselowerluckylunchlyingmagicmajormakermarchmariamatchmaybemayormeantmediametalmightminorminusmixedmodelmoneymonthmoralmotormountmousemouthmoviemusicneedsnevernewlynightnoisenorthnotednovelnurseoccuroceanofferoftenorderotheroughtpaintpanelpaperpartypeacepeterphasephonephotopiecepilotpitchplaceplainplaneplantplatepointpoundpowerpresspriceprideprimeprintpriorprizeproofproudprovequeenquickquietquiteradioraiserangerapidratioreachreadyreferrightrivalriverrobinrogerromanroughroundrouteroyalruralscalescenescopescoresenseservesevenshallshapesharesharpsheetshelfshellshiftshirtshockshootshortshownsightsincesixthsixtysizedskillsleepslidesmallsmartsmilesmithsmokesolidsolvesorrysoundsouthspacesparespeakspeedspendspentsplitspokesportstaffstagestakestandstartstatesteamsteelstickstillstockstonestoodstorestormstorystripstuckstudystuffstylesugarsuitesupersweettabletakentastetaxesteachteethterrytexasthankthefttheirthemetherethesethickthingthinkthirdthosethreethrewthrowtighttimestiredtitletodaytopictotaltouchtoughtowertracktradetraintreattrendtrialtriedtriestrucktrulytrusttruthtwiceunderundueunionunityuntilupperupseturbanusageusualvalidvaluevideovirusvisitvitalvoicewastewatchwaterwheelwherewhichwhilewhitewholewhosewomanwomenworldworryworseworstworthwouldwoundwritewrongwroteyieldyoungyouth";

export const wordsArr = (str) => {
  let arr = str.split("");
  let array = [];
  let wordArr = arr.map((letter) => {
    if (array.length < 5) {
      array.push(letter.toUpperCase());
    } else {
      array = [];
      array.push(letter.toUpperCase());
    }
    return array;
  });
  let count = 1;
  let finalArr = wordArr.filter(() => {
    if (count === 5) {
      count = 1;
      return true;
    } else {
      count++;
      return false;
    }
  });
  return finalArr;
};

export const pickWord = (wordArr) => {
  let randomNum = Math.floor(Math.random() * 466);
  return wordArr[randomNum];
};
